[package]
name = "isearch-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28"
ratatui = "0.29"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
qrcode = "0.14"
arboard = "3.4"
ureq = "3.3.0"
tl = "0.7.8"
pulldown-cmark = "0.13.4"
syntect = "5.3.0"
zip = "8.6.0"
percent-encoding = "2.3.2"
image = "0.25.10"
base64 = "0.23.0"
rusqlite = { version = "0.31.0", features = ["bundled"] }
serde_json = "1.0.151"
