name: Build Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    name: Build Linux Binaries (x86_64, aarch64, arm)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu, armv7-unknown-linux-gnueabihf

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install Cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross

      - name: Build standard x86_64-unknown-linux-gnu
        run: cross build --release --target x86_64-unknown-linux-gnu

      - name: Build standard aarch64-unknown-linux-gnu
        run: cross build --release --target aarch64-unknown-linux-gnu

      - name: Build standard armv7-unknown-linux-gnueabihf
        run: cross build --release --target armv7-unknown-linux-gnueabihf

      - name: Upload Linux x86_64 Artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: isearch-linux-x86_64
          path: target/x86_64-unknown-linux-gnu/release/isearch-cli
