name: Rustdoc Verification

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types:
      - published

jobs:
  rustdoc:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Generate Rustdoc
        env:
          RUSTDOCFLAGS: -D warnings
        run: cargo doc --no-deps --all-features
